name: 🧠 BrainsMath Feedback
description: Bug reports, suggestions, and general feedback for BrainsMath2
title: "[FEEDBACK] "
labels: ["feedback"]
body:
  - type: dropdown
    id: role
    attributes:
      label: Who are you?
      description: Helps us understand your perspective!
      options:
        - Developer
        - Typist
        - Math Enthusiast
        - Student
        - Other
    validations:
      required: false

  - type: textarea
    id: summary
    attributes:
      label: 💬 What would you like to share?
      description: Tell us about your idea, bug, or anything else.
      placeholder: e.g. I noticed a visual glitch on the challenge screen...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔁 Steps to Reproduce (for bugs)
      description: If you found a bug, help us see it too.
      placeholder: 1. Go to '...', 2. Click on '...'
    validations:
      required: false

  - type: input
    id: device
    attributes:
      label: 📱 Device Info (Optional)
      description: What device/browser/OS were you using?
      placeholder: e.g. Windows 11 / Chrome 123
    validations:
      required: false

  - type: textarea
    id: suggestions
    attributes:
      label: 🧠 Suggestions / Improvements?
      description: Any ideas to make BrainsMath better?
      placeholder: e.g. Add a mode that teaches multiplication tricks...
    validations:
      required: false
